version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql #容器的名称
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/db/:/var/lib/mysql/
      - $PWD/mysqld/:/var/run/mysqld/
      - $PWD/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf